apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-tests-python-gbainsxm
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/e2e-tests-python-gbainsxm:azure-3c3ead3314d6d502ab51d5b0f72e1c6cae7dccef
        name: container-image  
